name: Faker
on: push
jobs:
  test:
    name: Test the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: See if yarn is installed
        run: yarn -v

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test
