name: Faker
on: push
jobs:
  # test:
  #   name: Test the application
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run test
  #       run: npm run test

  #     - name: Show the dir
  #       run: ls -la
  build:
    name: Build function
    runs-on: ubuntu-latest
    # needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build function
        run: npm run build

      - name: Copy package.json
        run: cp package.json ./build

      - name: Install production dependencies
        run: |
          cd build
          npm install --only=prod

      - name: Zip the function
        run: zip -r function.zip .

      - name: Show content of the dir now
        run: ls -la
